### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by SzotsGabor** [Jakob256/PurplePanda#2]
Hi Jakob,

creating_KPk_Tablebase.cpp:18:10: fatal error: assignMoveList.h: No such file or directory
   18 | #include "assignMoveList.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Gabor Szots
CCRL testing group

BTW, I recommend including version number in the engine UCI id.

Edit: The exe in the package does not move on my PC.

**Comment by Jakob256** [comment]
Hi Gabor,

@error: you are right, in some update I renamed the move-generator and forgot to also change it in the KPk tablebase generator, as it was executed only once. It is now fixed.

@versionNumber: Thanks for the idea, it is now incorporated! Let me know if there are other things to improve.

@exe: Have you tried copying the two dll files from the dll folder in the same location as the engine? 

I have now added in the readme a short explanation of how to get the program running.

A huge thank you for maintaining the CCRL!
Jakob

**Comment by SzotsGabor** [comment]
Yes, compilation is successful now.

However, your exe still does not move, even with the dll's in their place. The exe I made following your instructions does move but the memory it uses is growing after every move. It starts at about 143 MB and ends at about 767 MB. At the beginning the growth is rapid then it slows down and saturates.

And one more suggestion: when you release a version perhaps you could put it into 'Releases'. That can be followed and users learn about new versions immediately.

**Comment by Jakob256** [comment]
Many good news:

@exe: I tried the exe on a friends computer and it also didn't work. After many tries, it seems I have fixed the problem. Now the latest version 12 (as well as the KPk generator) should work on all 64 bit Windows machines when copying the two dll files to the same folder.

@memory: The large memory usage was due to a growing hash-table. I've now limited its size to 128MB (and will keep any endgame tablebase below 32MB) to satisfy the CCRL rules.

@releases: I have now started using the 'Releases' feature. (You can tell I'm pretty new to using git/github. 😊) Thank you for the tip! Please let me know if you have any further suggestions.

Many thanks,
Jakob

**Comment by SzotsGabor** [comment]
You could make hash size and endgame cache size settable.
